export const CODING_DATA = [
  {
    id: 1,
    title: 'Admin Dashboard - Next.js',
    fulltitle: 'An Admin Dashboard application created with Next.js',
    client: 'https://github.com/nikkipurcell/nextjs-dashboard',
    role: 'Developer',
    imageSrc: '/coding_nextjs.jpg',
    imageBigSrc: '',
    brief: 'nextjs-dashboard',
    solution:
      'This application includes many of the features available in Next.js. I wrote it in TypeScript and Tailwind CSS. It is deployed using Vercel and has authentication through NextAuth.js. Some of the features include static and dynamic rendering, form validations, pagination, search, page layout components, crud functions, data fetching, and error handling.',
    technologies: ['Next.js, ', 'TypeScript, ', 'Prisma, ', 'Tailwind, ', 'Vercel, ', 'Postgres'],
    modal: false,
  },
  {
    id: 2,
    title: 'Crown Clothing - Ecommerce Website',
    fulltitle: 'A fullstack ecommerce retail clothing website',
    client: 'https://github.com/nikkipurcell/react-crwn-clothing',
    role: 'Developer',
    imageSrc: '/coding_crwn_clothing.jpg',
    imageBigSrc: '',
    brief: 'react-crwn-clothing',
    solution:
      'This fullstack app is an ecommerce site similar to shopify with login, authentication, shopping cart, and connected to a Stripe test portal. I wrote it using React.',
    technologies: ['React, ', 'Redux, ', 'React Router, ', 'Context API, ', 'Firebase, ', 'Stripe API'],
    modal: false,
  },
  {
    id: 3,
    title: 'Email App - MySQL',
    fulltitle: 'An email application that uses a mySQL database, Express, and Node.js',
    client: 'https://github.com/nikkipurcell/mysql-join-us',
    role: 'Developer',
    imageSrc: '/coding_mysql.jpg',
    imageBigSrc: '',
    brief: 'mysql-join-us',
    solution:
      'I created this JavaScript app that uses a mySQL database, Express, and Node.js. This simple JavaScript web page asks the user to enter an email address and displays the total amount of users in the DB. When a new email is submitted, the user count will increase on the page.',
    technologies: ['JavaScript, ', 'Express, ', 'Node.js, ', 'MySQL, ', 'Body Parser, ', 'EJS'],
    modal: false,
  },
  {
    id: 4,
    title: 'Mapty - A JavaScript App Using The Geolocation API',
    fulltitle: 'A an interactive app that uses the Geolocation API',
    client: 'https://github.com/nikkipurcell/js-mapty',
    role: 'Developer',
    imageSrc: '/coding_mapty.jpg',
    imageBigSrc: '',
    brief: 'js-mapty',
    solution:
      'This JavaScript app uses the Geolocation API to collect latitude and longitude coordinates of the user. When a user clicks on the map, they can fill out a form to create either a cycling object or running object and a marker with that data will be added at the location that was clicked. The user can also click the data objects logged in the sidebar to allow the map to center on the desired workout marker.',
    technologies: ['JavaScript, ', 'Geolocation API, ', 'ES6 classes'],
    modal: false,
  },
  {
    id: 5,
    title: 'Bankist - A JavaScript Banking App',
    fulltitle: 'A demo banking application',
    client: 'https://github.com/nikkipurcell/js-bankist',
    role: 'Developer',
    imageSrc: '/coding_bankist.jpg',
    imageBigSrc: '',
    brief: 'js-bankist',
    solution:
      "I created this banking application using JavaScript. After logging in, the user can transfer money to another user, request a loan amount from the bank or close their account. Money values are displayed based on the user's set locale (using the Internationalization API). A user can see a current balance, a list of deposits or withdrawals, total deposits, total withdrawals and interest earned. There is also a sort feature and a logout timer set to 2 minutes of inactivity.",
    technologies: ['JavaScript, ', 'DOM Manipulation, ', 'Internationalization API '],
    modal: false,
  },
];
